# Generated by Django 4.0.5 on 2022-06-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='short_description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
